# Generated by Django 5.1.1 on 2025-06-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
