# Generated by Django 5.1.1 on 2025-06-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_payment_method_alter_order_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
