# Generated by Django 5.1.1 on 2025-06-25 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_is_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationlog',
            old_name='registered_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='registrationlog',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=45),
        ),
        migrations.AlterField(
            model_name='registrationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
