# Generated by Django 5.1.1 on 2025-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_registered_at_registrationlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
